apiVersion: v1
kind: Service
metadata:
  name: docker-host
  labels:
    {{- include "lagoon-remote.dockerHost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dockerHost.service.type }}
  ports:
    - port: {{ .Values.dockerHost.service.port }}
      targetPort: docker-daemon
      protocol: TCP
      name: docker-daemon
  selector:
    {{- include "lagoon-remote.dockerHost.selectorLabels" . | nindent 4 }}
