{{- if .Values.dockerHost.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-remote.dockerHost.serviceAccountName" . }}
  labels:
    {{- include "lagoon-remote.dockerHost.labels" . | nindent 4 }}
{{- end }}
