{{- if and .Values.dockerHost.serviceAccount.create .Values.global.openshift -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lagoon-remote.dockerHost.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lagoon-remote.dockerHost.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lagoon-remote.dockerHost.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-remote.dockerHost.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
