apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-remote.kubernetesBuildDeploy.serviceAccountName" . }}
  labels:
    {{- include "lagoon-remote.kubernetesBuildDeploy.labels" . | nindent 4 }}
  {{- with .Values.kubernetesBuildDeploy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
