{{- if .Values.mxoutHost -}}
apiVersion: v1
kind: Service
metadata:
  name: mxout
  labels:
    {{- include "lagoon-remote.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.mxoutHost | quote }}
{{- end }}
