apiVersion: v1
kind: Service
metadata:
  name: router-logs
  labels:
    {{- include "lagoon-remote.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.logsDispatcherHost | quote }}
