apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-build-deploy.serviceAccountName" . }}
  labels:
    {{- include "lagoon-build-deploy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
