apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-core.broker.serviceAccountName" . }}
  labels:
    {{- include "lagoon-core.broker.labels" . | nindent 4 }}
  {{- with .Values.broker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
