{{- if .Values.drushAlias.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-core.drushAlias.fullname" . }}
  labels:
    {{- include "lagoon-core.drushAlias.labels" . | nindent 4 }}
spec:
  type: {{ .Values.drushAlias.service.type }}
  ports:
  - port: {{ .Values.drushAlias.service.port }}
    targetPort: http-8080
    name: http-8080
  selector:
    {{- include "lagoon-core.drushAlias.selectorLabels" . | nindent 4 }}
{{- end }}
