{{/*
This somewhat complex logic is intended to:
  * generate a random secret value automatically on chart install
  * not overwrite the randomly generated value on upgrade
  * allow overriding if the value is explicitly defined
*/}}
{{- $data := index (lookup "v1" "Secret" .Release.Namespace (print (include "lagoon-core.fullname" . ) "-jwtsecret")) "data" | default dict }}
{{- $jwtSecret := coalesce .Values.jwtSecret (ternary (randAlpha 32) (index $data "JWTSECRET" | default "" | b64dec) (index $data "JWTSECRET" | empty)) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-core.fullname" . }}-jwtsecret
  labels:
    {{- include "lagoon-core.labels" . | nindent 4 }}
stringData:
  JWTSECRET: {{ $jwtSecret | quote }}
