{{- if .Values.sshPortal.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-core.sshPortal.serviceAccountName" . }}
  labels:
    {{- include "lagoon-core.sshPortal.labels" . | nindent 4 }}
  {{- with .Values.sshPortal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
