{{- if .Values.sshPortal.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-core.sshPortal.fullname" . }}
  labels:
    {{- include "lagoon-core.sshPortal.labels" . | nindent 4 }}
stringData:
  HOSTKEY_RSA: |
    {{- required "A valid .Values.sshHostKeyRSA is required!" .Values.sshHostKeyRSA | nindent 4 }}
  HOSTKEY_ED25519: |
    {{- required "A valid .Values.sshHostKeyED25519 is required!" .Values.sshHostKeyED25519 | nindent 4 }}
{{- end }}
