{{- if .Values.webhookHandler.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-core.webhookHandler.fullname" . }}
  labels:
    {{- include "lagoon-core.webhookHandler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookHandler.service.type }}
  ports:
  - port: {{ .Values.webhookHandler.service.port }}
    targetPort: http-3000
    name: http-3000
  selector:
    {{- include "lagoon-core.webhookHandler.selectorLabels" . | nindent 4 }}
{{- end }}
